package group6.it.ou.sportfacilitybooking.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_PAYMENT_SUCCESS,
    BOOKING_PAYMENT_FAILED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    CHECK_IN,
    REVIEW_REPLY,
    FACILITY_CREATED,
    FACILITY_APPROVED,
    FACILITY_REJECTED,
    FACILITY_CANCELLED_BY_ADMIN,
    REFUND_PROCESSED
}
